site_name: mayankpant
theme:
  name: material

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mayank-pant
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/soyank_76
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mayank-pant76/

copyright: |
  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>